### ISSUE TITLE
error while adding plugin

### ISSUE THREAD

**Issue by basssment** [d-EScape/MotionShades-for-Domoticz#1]
Hi d-EScape,

I found your plugin and want to use it with my brel blinds
I Found out that the motion blinds of OGstarkiller works with my blinds and hub
now i added your plugin to domoticz but get the following error:

> 
 Error: (MotionShades) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/MotionShades-for-Domoticz/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.7/dist-packages'.
 Error: (Blinds) Module Import failed, exception: 'ModuleNotFoundError'
 Error: (Blinds) Module Import failed: ' Name: motionblinds'
 Error: (Blinds) Error Line details not available.
>
What could be wrong in this case?

**Comment by d-EScape** [comment]
Hi basement,
Looks like you didn’t install the required module. As described in the readme: “Requires https://github.com/starkillerOG/motion-blinds. Thanks to @starkillerOG for providing the python module!l

**Comment by basssment** [comment]
@d-EScape,
yes i did install them..

#pip install motionblinds
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: motionblinds in ./.local/lib/python3.7/site-packages (0.5.3)
Requirement already satisfied: pycryptodomex in ./.local/lib/python3.7/site-packages (from motionblinds) (3.10.1)

**Comment by d-EScape** [comment]
Domoticz might be using a different python environment (root) than the one you used to install the module (pi?).

**Comment by basssment** [comment]
yes i did install from pi
