### ISSUE TITLE
100% and 0%

### ISSUE THREAD

**Issue by hans1nl** [d-EScape/MotionShades-for-Domoticz#2]
I love de MotionShades-for-Domoticz! After the last update Domoticz i can't give the commands 0% or 100% to mij motionblinds. The other commands between 0 and 100 just works ok. Anyone got a hint for me what to do?

**Comment by d-EScape** [comment]
I have tested both the stable and latest beta release of Domoticz and I am able to set the blinds to 0 or 100 without any issues by json url and by user-interface. In what way are you trying to "give commands"?

The plugin has only been tested with coulisse roller blinds. Other blinds might behave differently. You can set some of the blinds behavior by editing the settings for the specific blind device in Domoticz. See [https://www.domoticz.com/wiki/Blinds](url)

**Comment by hans1nl** [comment]
@d-EScape , tnx for your reply!
It took me two days to find out that the files i dit use where not compatibel.
I did use the plugin.py version="2.2 on the new motionblind 0.6.19
After the update to version 2.3 everything is working great!

**Comment by d-EScape** [comment]
Glad you could fix it.
